name: Java Organization CI

on:
  env:
    APP_PATH: ./

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone git repository
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Run build with Gradle Wrapper
        run: ./${{ vars.APP_PATH }}/gradlew build